@startuml

class ExchangeValue {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String from_my;

    private String to_my;

    private BigDecimal conversionMultiple;
    private int port;
}



@enduml